* debian/control:   - add build-dep on dh-systemd. * debian/lightdm.postinst:   - handle symlinks for systemd service files according to the currently     selected display manager. * debian/lightdm.service:   - add systemd service file, thanks Martin Pitt for the work.closes: #733220 * debian/rules:   - use dh systemd addon and configure it to not start the lightdm service     at once.

diff --git a/debian/lightdm.postinst b/debian/lightdm.postinst
--- a/debian/lightdm.postinst
+++ b/debian/lightdm.postinst
@@ -62,6 +62,16 @@ fi
 if [ "$1" = "configure" ];
 then
   invoke-rc.d dbus reload || true
+
+  # set default-display-manager systemd service link according to our config
+  if [ -e "$DEFAULT_DISPLAY_MANAGER_FILE" -a -d /etc/systemd/system/ ]; then
+    SERVICE=/lib/systemd/system/$(basename $(cat "$DEFAULT_DISPLAY_MANAGER_FILE")).service
+    if [ -e "$SERVICE" ]; then
+      ln -sf "$SERVICE" /etc/systemd/system/display-manager.service
+    else
+      echo "ERROR: $SERVICE is the selected default display manager but does not exist" >&2
+    fi
+  fi
 fi
 
 #DEBHELPER#
